name: CI_mac
on: [push, pull_request]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          #- 'nightly'
        os:
          - macos-11
        arch:
          - x64          
    steps:
      - uses: actions/checkout@v2
      - name: Build MacPorts
        run: |
              git clone https://github.com/macports/macports-base
              cd macports-base
              set -eu
              ./configure
              make -j$(sysctl -n hw.activecpu)
      - name: Install MacPorts
        run:  |     
              cd macports-base 
              sudo make install
              /opt/local/bin/port version
              sudo /opt/local/bin/port -v -N selfupdate
      - name: Install BART dependency
        run: |
              sudo /opt/local/bin/port install -N fftw-3-single 
              sudo /opt/local/bin/port install -N gcc10
              sudo /opt/local/bin/port install -N libpng 
              sudo /opt/local/bin/port install -N openblas
              sudo /opt/local/bin/port -q contents gcc10 | grep -E '/s?bin/'
              sudo /opt/local/bin/port select --set gcc mp-gcc10
              brew install libomp
      - name: Install BART
        run: |        
              git clone https://github.com/mrirecon/bart
              cd bart
              git checkout 7aeae14c58b4358fa9e84900b65a38add258607c
              CC=gcc-10 make
      - name: Test BART
        run: |
              cd bart
              pwd
              ls -l bart
              ./bart version
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info