name: CI_mac
on: [push, pull_request]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          #- 'nightly'
        os:
          - macOS-latest
        arch:
          - x64          
    steps:
      - uses: actions/checkout@v2
      - run: |
              git clone https://github.com/mrirecon/bart
              cd bart
              git checkout 7aeae14c58b4358fa9e84900b65a38add258607c
      - run: |
              cd bart
              pwd
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info